// RunCat: a cat that runs faster the busier the CPU is, gets fatter the more
// memory is in use, and turns yellow then red as that memory gets serious.
//
// LOCAL ADDITION to the OmaStats plugin (not upstream). It is a readout like
// UI.BarReadout -- the widget hands it a CPU percentage and it reports clicks
// back -- so the bar holds one OmaStats entry and the panel anchors under the
// cat rather than under a separate placeholder widget.
//
// The CPU number comes from the plugin's own sampler; nothing here reads
// /proc. The load drives the frame *interval*, not the artwork.

import QtQuick
import QtQuick.Effects
import Quickshell.Io
import qs.Commons
import "../Model.js" as Model

Item {
  id: root

  // Both 0-100, straight from OmaStatsService's snapshot.
  property real cpu: 0
  property real memory: 0
  property color foreground: Color.bar.text

  signal activated(int button)

  // Which sprite set to draw. Frames live in ui/frames/<runner>_f<0-3>_<1-5>.svg
  // and are generated by tools/make-runner.py.
  property string runner: "cat"

  readonly property int frameCount: 5
  readonly property int fatLevels: 4
  property int frame: 0

  // Smoothed so the cat does not lurch on a single spiky sample.
  property real smoothed: 0
  onCpuChanged: root.smoothed = root.smoothed * 0.6 + Math.max(0, Math.min(100, root.cpu)) * 0.4

  // CPU sets the pace: idle trots at ~200 ms a frame, pegged sprints at ~30 ms.
  readonly property int frameInterval: Math.max(30, Math.round(200 - root.smoothed * 1.7))

  // Memory sets the waistline: a quarter of RAM per notch, so 0-24% is a lean
  // cat and 75%+ is a proper chonk. Each level is its own set of frames rather
  // than a scale transform -- stretching just makes a tall cat, not a fat one.
  readonly property int fatness: Math.max(0, Math.min(root.fatLevels - 1,
    Math.floor(Math.max(0, Math.min(100, root.memory)) / (100 / root.fatLevels))))

  // The waistline says how much memory is in use; the colour says whether that
  // is getting serious. Level 2 (50-74%) goes yellow, level 3 (75%+) goes red.
  // Levels 0 and 1 stay the bar's ordinary text colour, so the cat only draws
  // attention when there is something to look at.
  //
  // Red is a real theme role: Color.qml promotes colors.toml's `red` to
  // Color.urgent. Yellow is NOT -- Color.qml only lifts foreground, background,
  // accent, muted and red out of colors.toml -- so the theme's yellow is read
  // from that same file rather than hardcoded, which is the whole point of
  // following the theme.
  property color warnColor: root.mix(root.foreground, Color.urgent, 0.5)

  property color catColor: root.fatness >= 3 ? Color.urgent
                         : root.fatness >= 2 ? root.warnColor
                         : root.foreground
  // Eased, because memory hovers around a threshold: without this the cat
  // flickers between two colours as the reading crosses 50% back and forth.
  Behavior on catColor { ColorAnimation { duration: 250 } }

  function mix(a, b, t) {
    return Qt.rgba(a.r + (b.r - a.r) * t,
                   a.g + (b.g - a.g) * t,
                   a.b + (b.b - a.b) * t, 1)
  }

  // Same regex Color.qml uses on the same file, so a key it would accept is a
  // key this accepts. Preference order matters: a theme may define several
  // yellows and `yellow` is the one its palette treats as canonical.
  function parseWarn(toml) {
    const want = ["yellow", "bright_yellow", "orange"]
    const found = ({})
    const lines = String(toml).split("\n")
    for (var i = 0; i < lines.length; i++) {
      const m = lines[i].match(/^\s*([A-Za-z0-9_-]+)\s*=\s*["']?(#[0-9A-Fa-f]{6})/)
      if (m && want.indexOf(m[1]) !== -1 && !found[m[1]]) found[m[1]] = m[2]
    }
    for (var j = 0; j < want.length; j++)
      if (found[want[j]]) return found[want[j]]
    // No yellow anywhere in the palette: sit halfway between text and red, so
    // level 2 still reads as "warmer than normal" instead of being
    // indistinguishable from level 3.
    return root.mix(root.foreground, Color.urgent, 0.5)
  }

  FileView {
    id: themePalette
    path: Color.currentThemePath + "/colors.toml"
    watchChanges: true
    printErrors: false
    onLoaded: root.warnColor = root.parseWarn(text())
  }

  // `currentThemePath` is a fixed path through a symlink, so switching themes
  // repoints the link without changing the string -- a file watcher on it may
  // never fire. Color.urgent changing is the reliable signal that the palette
  // was reloaded, so re-read on that too.
  Connections {
    target: Color
    function onUrgentChanged() { themePalette.reload() }
  }

  // Sized against the optical square every other bar glyph is drawn in, then
  // trimmed a little: the frames run edge to edge (ear tips to paws) where a
  // glyph carries its own internal padding, so a full-canvas cat reads bigger
  // than its neighbours. The frames use a 60x32 viewBox.
  // Sized off icon-font, NOT icon-canvas.
  //
  // BarIconButton hands drawn icons the `icon-canvas` box and renders glyphs
  // at `icon-font`; they are independent tokens and omarchy's defaults make
  // them 16 and 13. Taking runnerScale (0.65) of the canvas therefore put the
  // cat at 0.65*16 = 10.4 against glyphs at 13 -- measured in a stock theme,
  // 32.7% of bar height beside a robot at 55.8%.
  //
  // 1.847 is the canvas size at which a drawn icon matches an SF Symbols
  // glyph at the same icon-font (derived in omarchy-control-center's
  // ui/CcSwitchIcon.qml from switch.2's 0.933 ink ratio). runnerScale then
  // trims from there, which is what it was always meant to do. At icon-font
  // 15 this gives 15 * 1.847 * 0.65 = 18, the value it already had, so the
  // themes that tuned against it do not move.
  readonly property int catHeight: Math.round(Style.bar.iconFont * 1.847 * Model.runnerScale(root.runner))
  readonly property int catWidth: Math.round(catHeight * 60 / 32)

  // The frames do NOT run edge to edge, despite what the catHeight comment
  // above says. Rendered and measured across catalpha's five frames, the ink
  // fills 0.767 to 0.833 of the 60x32 viewBox horizontally -- mean 0.80. A
  // constant is used rather than the per-frame extent on purpose: a box that
  // tracked the animation would shove every icon beside it back and forth
  // five times a second.
  readonly property real paintedWidth: catWidth * 0.80

  // Padding, not decoration: the cat's silhouette is ~2x wider than a glyph, so
  // the same slack a glyph gets inside iconSlot leaves the cat looking wedged
  // against its neighbours.
  //
  // Two behaviours, picked by whether the theme sets [bar] icon-gap:
  //
  //   unset (0) -- every theme but macos-light: the hand-measured
  //     Style.space(16) this has always used, so nothing changes for them.
  //   set -- take the same padding the glyph icons take, measured from the
  //     same thing (painted ink), so the gap matches by construction.
  implicitWidth: Style.bar.iconGap > 0
               ? Math.round(paintedWidth + Style.bar.iconGap)
               : catWidth + Style.space(16)
  implicitHeight: Style.bar.iconSlot

  Timer {
    interval: root.frameInterval
    running: true
    repeat: true
    onTriggered: root.frame = (root.frame + 1) % root.frameCount
  }

  Image {
    id: cat
    anchors.centerIn: parent
    width: root.catWidth
    height: root.catHeight
    // The runner is a name, not a hardcoded cat: every runner ships the same
    // 4 fatness x 5 frame grid under that name, so swapping one in is a string.
    source: Qt.resolvedUrl("frames/" + root.runner + "_f" + root.fatness + "_" + (root.frame + 1) + ".svg")
    sourceSize.width: root.catWidth * Screen.devicePixelRatio
    sourceSize.height: root.catHeight * Screen.devicePixelRatio
    fillMode: Image.PreserveAspectFit
    smooth: true
    cache: true
    visible: false
  }

  // The frames are white; recolour them to the bar's text colour so the cat
  // follows the Omarchy theme like every other widget.
  MultiEffect {
    anchors.centerIn: parent
    width: root.catWidth
    height: root.catHeight
    source: cat
    colorization: 1.0
    colorizationColor: root.catColor
    opacity: mouse.containsMouse ? 1.0 : 0.88
    Behavior on opacity { NumberAnimation { duration: 120 } }
  }

  MouseArea {
    id: mouse
    anchors.fill: parent
    hoverEnabled: true
    acceptedButtons: Qt.LeftButton | Qt.RightButton | Qt.MiddleButton
    onClicked: function(e) { root.activated(e.button) }
  }
}
